; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-core]
platform = espressif32@6.3.2
board = m5stack-core-esp32
framework = arduino
board_build.partitions = no_ota.csv
upload_speed = 1500000
monitor_speed = 115200
build_flags =
    -DRUDICORE_ENABLE_BLUETOOTH=1
    -DADC_DATA_BUF_SIZE=20000

lib_deps = 
    https://github.com/rudicore-M5-libs/M5Stack.git#819a1f9
    https://github.com/rudicore-M5-libs/M5ez.git
    https://github.com/rudicore-M5-libs/Adafruit_TCS34725
    https://github.com/rudicore-M5-libs/Adafruit_MCP4725.git
    https://github.com/rudicore-M5-libs/Adafruit_BMP280_Library.git
    https://github.com/rudicore-M5-libs/M5-ENVII-lib.git 
    https://github.com/rudicore-M5-libs/ST_HW_HC_SR04.git
    https://github.com/rudicore-M5-libs/Adafruit_VL53L0X.git
    https://github.com/rudicore-M5-libs/M5-TCA9548A-lib.git
    https://github.com/rudicore-M5-libs/TinyGPSPlus.git
    https://github.com/rudicore-M5-libs/espsoftwareserial.git#eb4b290 
    https://github.com/rudicore-M5-libs/sds-dust-sensors-arduino-library.git
    https://github.com/rudicore-M5-libs/Adafruit_SGP30.git
    https://github.com/rudicore-M5-libs/HX711.git
    https://github.com/rudicore-M5-libs/M5Unit-PbHub.git
    https://github.com/rudicore-M5-libs/M5-porthub-lib.git
    https://github.com/rudicore-M5-libs/M5_BMM150.git#f416310 
    https://github.com/rudicore-M5-libs/M5Unit-KMeter.git
    https://github.com/rudicore-M5-libs/ESP32AnalogRead.git#17a157a 
    https://github.com/rudicore-M5-libs/DFRobot_OxygenSensor.git
    https://github.com/rudicore-M5-libs/M5-ADS1100-lib.git
    https://github.com/rudicore-M5-libs/INA.git
    https://github.com/rudicore-M5-libs/GP8403.git
    https://github.com/rudicore-M5-libs/LTR390.git    
    https://github.com/rudicore-M5-libs/M5Unit-Miniscale.git
    https://github.com/rudicore-M5-libs/Arduino-ADXL345.git
    https://github.com/rudicore-M5-libs/M5-ADS1115.git
    https://github.com/rudicore-M5-libs/M5Stack-MLX90640.git

[env:m5stack-core-no-bt]
extends = env:m5stack-core
build_flags =
    -DRUDICORE_ENABLE_BLUETOOTH=0
    -DADC_DATA_BUF_SIZE=0
    -DADC_DATA_BUF_RESERVE_BYTES=32768
lib_ignore =
    BluetoothSerial
    BLE
